services:
  # Backend Service
  - type: web
    name: winery-sales-simulator-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 3001
      - key: FIREBASE_API_KEY
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_API_KEY
      - key: FIREBASE_AUTH_DOMAIN
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_AUTH_DOMAIN
      - key: FIREBASE_PROJECT_ID
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_PROJECT_ID
      - key: FIREBASE_STORAGE_BUCKET
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_STORAGE_BUCKET
      - key: FIREBASE_MESSAGING_SENDER_ID
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_MESSAGING_SENDER_ID
      - key: FIREBASE_APP_ID
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_APP_ID
      - key: CLAUDE_API_KEY
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: CLAUDE_API_KEY
    healthCheckPath: /api/health
    cors:
      origins:
        - https://winery-sales-simulator.onrender.com
        - http://localhost:3000
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Content-Type
        - Authorization
        - x-user-id
      allowCredentials: true
      maxAge: 86400

  # Frontend Service
  - type: web
    name: winery-sales-simulator-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: winery-sales-simulator-backend
          type: url
      - key: REACT_APP_FIREBASE_API_KEY
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_API_KEY
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_AUTH_DOMAIN
      - key: REACT_APP_FIREBASE_PROJECT_ID
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_PROJECT_ID
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_STORAGE_BUCKET
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_MESSAGING_SENDER_ID
      - key: REACT_APP_FIREBASE_APP_ID
        fromService:
          name: winery-sales-simulator-backend
          type: env
          property: FIREBASE_APP_ID
    healthCheckPath: /health
    autoDeploy: true
    dependsOn:
      - winery-sales-simulator-backend 