services:
  - type: web
    name: winery-sales-simulator-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: CLAUDE_API_KEY
        value: "your-claude-api-key-here"
      - key: ELEVENLABS_API_KEY
        value: "your-elevenlabs-api-key-here"
      - key: ELEVENLABS_ANN_VOICE_ID
        value: "your-ann-voice-id-here"
      - key: ELEVENLABS_GABRIELLA_VOICE_ID
        value: "your-gabriella-voice-id-here"
      - key: ELEVENLABS_RUSSELL_VOICE_ID
        value: "your-russell-voice-id-here"
      - key: ELEVENLABS_MIKE_VOICE_ID
        value: "your-mike-voice-id-here"
      - key: REACT_APP_FIREBASE_API_KEY
        value: "your-firebase-api-key-here"
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        value: "your-firebase-auth-domain-here"
      - key: REACT_APP_FIREBASE_PROJECT_ID
        value: "your-firebase-project-id-here"
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        value: "your-firebase-storage-bucket-here"
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        value: "your-firebase-messaging-sender-id-here"
      - key: REACT_APP_FIREBASE_APP_ID
        value: "your-firebase-app-id-here"

  - type: web
    name: winery-sales-simulator-frontend
    env: static
    buildCommand: cd client && npm install && CI=false npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://winery-sales-simulator-backend.onrender.com"
      - key: REACT_APP_FIREBASE_API_KEY
        value: "your-firebase-api-key-here"
      - key: REACT_APP_FIREBASE_AUTH_DOMAIN
        value: "your-firebase-auth-domain-here"
      - key: REACT_APP_FIREBASE_PROJECT_ID
        value: "your-firebase-project-id-here"
      - key: REACT_APP_FIREBASE_STORAGE_BUCKET
        value: "your-firebase-storage-bucket-here"
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        value: "your-firebase-messaging-sender-id-here"
      - key: REACT_APP_FIREBASE_APP_ID
        value: "your-firebase-app-id-here" 